apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-jqfnpbrt
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-jqfnpbrt:acc2ddf966b62aa82041cfb1e41accb160c26431@sha256:c7ae62137f97a2d66bcd4872b7eda486f1b8ed990d2c525c1135fa3542030e27
        name: container-image  
